import 'package:weather_icons/weather_icons.dart';

List<String> weatherAvailabre = [
  'Tempestade forte',
  'Tempestade tropical',
  'Furacão',
  'Tempestades severas',
  'Tempestades',
  'Misto de neve e chuva',
  'Misto chuva e gelo',
  'Misto neve e gelo',
  'Geada fina',
  'Chuviscos',
  'Congelamento chuva',
  'Alguns chuviscos',
  'Neve baixa',
  'Tempestade com neve',
  'Ventania com neve',
  'Neve',
  'Granizo',
  'Gelo',
  'Poeira',
  'Neblina',
  'Tempestade de areia',
  'Fumacento',
  'Vento acentuado',
  'Ventania',
  'Tempo frio',
  'Tempo nublado',
  'Tempo limpo',
  'Parcialmente nublado',
  'Ensolarado',
  'Estrelado',
  'Ensolarado com muitas nuvens',
  'Misto chuva e granizo',
  'Ar quente',
  'Tempestades isoladas',
  'Trovoadas dispersas',
  'Chuvas esparsas',
  'Pesados neve',
  'Chuviscos com neve',
  'Neve pesada',
  'Sol com poucas nuvens',
  'Chuva',
  'Queda de neve',
  'Tempestades isoladas',
  'Serviço não disponível'
];
List assetWeather = [
  'storm',
  'NS',
  WeatherIcons.tornado,
  'storm',
  'storm',
  'snow',
  'snow',
  'snow',
  'partly-shower',
  'partly-shower',
  'snow-sunny',
  'partly-shower',
  'snow-sunny',
  'snow-sunny',
  'snow-sunny',
  'snow-sunny',
  'snow-sunny',
  'snow-sunny',
  'mist',
  'windy',
  WeatherIcons.sandstorm,
  WeatherIcons.smog,
  WeatherIcons.strong_wind,
  WeatherIcons.wind,
  WeatherIcons.thermometer_exterior,
  'windy',
  'sunny',
  'partly-cloudy',
  'sunny',
  WeatherIcons.stars,
  'partly-cloudy',
  'snow',
  WeatherIcons.thermometer,
  'partly-cloudy',
  'thunder',
  'partly-shower',
  'snow-sunny',
  'snow-sunny',
  'snow-sunny',
  'partly-cloudy',
  'storm',
  'snow',
  'stormshowersday',
  WeatherIcons.na
];
const cities = [
  'Rio de Janeiro, RJ',
  'São Paulo,SP',
  'Canadá,ON',
  'Belo Horizonte, MG'
];
